### ISSUE TITLE
Strange simulator behavior when external function calls have side effects

### ISSUE THREAD

**Issue by Lqs66** [UPPAALModelChecker/uppaal-libs#15]
hi.
I have tested the functionality of external function on UPPAAL-5 with the following code:

The source code of libexternal.so is as follows:
```
#include <cmath>

static int number = 42; // internal state, be careful

#ifdef __cplusplus
extern "C" { // tells C++ compiler to use C symbol name mangling (C compiler ignores)
#endif // __cplusplus

int get_number()
{   // is not free from side-effects, when set_number is used
    return number++;
}

#ifdef __cplusplus
} // end of "C" symbol name mangling
#endif // __cplusplus
```
The UPPAAL model is as follows:

![image](https://github.com/UPPAALModelChecker/uppaal-libs/assets/62269820/8042734d-d7af-42a6-a89c-ec53fec841d1)

When I use this model for symbolic simulation, it gives me values for the ` variable a` that do not match the expectations.
It doesn't return `number++` each time as defined by the `get_number` function, it actually increases `number` by 3 each time.

![image](https://github.com/UPPAALModelChecker/uppaal-libs/assets/62269820/1527f51c-f42a-40d7-882a-2d869a0a4a0c)
![image](https://github.com/UPPAALModelChecker/uppaal-libs/assets/62269820/5d1b2fd8-4581-49ed-bed2-e4add7d7d0d9)

My complete model file is below:

[test.xml.txt](https://github.com/UPPAALModelChecker/uppaal-libs/files/14954168/test.xml.txt)

**Comment by mikucionisaau** [comment]
Due to the ***side effects*** inside the library, there is no way the simulator can be fixed, because the simulator allows arbitrary order of transition execution (one can go far ahead in the simulation and then come back to a second transition and choose another, or reexecute again).

Similarly with symbolic queries: the order of successor computation is controlled by exploration options (and then complicated state space optimization techniques), hence the computed value of such functions is not well defined.

So in short: ***no side effects are allowed,*** the function calls must be ***deterministic*** (for any given argument values it must produce the same result when called with the same values, always).
The only reasonable side effect could be [memoization](https://en.wikipedia.org/wiki/Memoization)/caching implementation, but it still needs to be deterministic.

P.S. We have a very similar situation with `meta` variables, potentially storing the side-effects and then the simulator behaves also in unpredictable ways. The only valid use of `meta` variables is to store and use the values through `meta` variables on the same (synchronizing) transition, otherwise their values are undefined.

**Comment by Lqs66** [comment]
> Due to the _**side effects**_ inside the library, there is no way the simulator can be fixed, because the simulator allows arbitrary order of transition execution (one can go far ahead in the simulation and then come back to a second transition and choose another, or reexecute again).
> 
> Similarly with symbolic queries: the order of successor computation is controlled by exploration options (and then complicated state space optimization techniques), hence the computed value of such functions is not well defined.
> 
> So in short: _**no side effects are allowed,**_ the function calls must be _**deterministic**_ (for any given argument values it must produce the same result when called with the same values, always). The only reasonable side effect could be [memoization](https://en.wikipedia.org/wiki/Memoization)/caching implementation, but it still needs to be deterministic.
> 
> P.S. We have a very similar situation with `meta` variables, potentially storing the side-effects and then the simulator behaves also in unpredictable ways. The only valid use of `meta` variables is to store and use the values through `meta` variables on the same (synchronizing) transition, otherwise their values are undefined.

Thank you for your very detailed response!

**Comment by mikucionisaau** [comment]
I have added a section on assumptions about the external functions:
https://docs.uppaal.org/language-reference/system-description/declarations/external-functions/#assumptions
I hope it explains the situation better.
